import type { ThemeConfig } from "./types";

/**
 * Cloned from zat, then tuned via /config for newzat videos/assets.
 */
export const newzatTheme: ThemeConfig = {
  id: "newzat",
  landscape: {
    baloot: {
      score: {
        video: "/videos/newzat/Corner_Score.webm",
        videoWidth: 1920,
        videoHeight: 1080,
        introStartSec: 0,
        introEndSec: 4,
        mountDelaySec: 2.15,
        mountFadeSec: 0.5,
        scoreTweenSec: 0.75,
        unmountFadeSec: 0.5,
        outroPlaybackRate: 3,
        team1: {
          wrapLeftPx: 1037,
          wrapTopPx: 100,
          wrapWidthPx: 324,
          wrapHeightPx: 62,
          nameLeftPx: 85,
          nameTopPx: 14,
          nameWidthPx: 200,
          scoreLeftPx: 0,
          sponsorSrc: "/images/newzat/zat_white.svg",
          sponsorLeftPx: 314,
          nameColor: "#ffffff",
          nameFontFamily: "DinNextRegular",
          nameFontSizePx: 28,
          scoreColor: "#ffffff",
          scoreFontSizePx: 26,
        },
        team2: {
          wrapLeftPx: 552,
          wrapTopPx: 105,
          wrapWidthPx: 324,
          wrapHeightPx: 43,
          nameLeftPx: 50,
          nameTopPx: 4,
          nameWidthPx: 200,
          scoreLeftPx: 269,
          sponsorSrc: "/images/newzat/kfc.png",
          sponsorLeftPx: -52,
          sponsorTopPx: -13,
          sponsorWidthPx: 70,
          sponsorHeightPx: 70,
          nameColor: "#ffffff",
          nameFontFamily: "DinNextRegular",
          nameFontSizePx: 28,
          scoreColor: "#ffffff",
          scoreFontSizePx: 26,
        },
      },
      detail: {
        video: "/videos/newzat/Full_Score.webm",
        videoWidth: 1920,
        videoHeight: 1080,
        introStartSec: 0,
        introEndSec: 3.5,
        mountDelaySec: 1.75,
        mountFadeSec: 0.75,
        unmountFadeSec: 1,
        outroPlaybackRate: 2,
        mainHoldMs: 1,
        team1: {
          wrapLeftPx: 1003,
          wrapTopPx: 132,
          wrapWidthPx: 428,
          wrapHeightPx: 80,
          nameLeftPx: 111,
          nameWidthPx: 257,
          scoreLeftPx: 14,
          detailLeftPx: 0,
          detailTopPx: 300,
          detailWidthPx: 85,
          sponsorSrc: "/images/newzat/zat_white.svg",
          sponsorLeftPx: 313,
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          scoreColor: "#ffffff",
          scoreFontSizePx: 34,
        },
        team2: {
          wrapLeftPx: 475,
          wrapTopPx: 132,
          wrapWidthPx: 428,
          wrapHeightPx: 97,
          nameLeftPx: 115,
          nameWidthPx: 257,
          scoreRightPx: -1,
          detailRightPx: 0,
          detailTopPx: 300,
          detailWidthPx: 85,
          sponsorSrc: "/images/newzat/zat_white.svg",
          sponsorLeftPx: 23,
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          scoreColor: "#ffffff",
          scoreFontSizePx: 35,
        },
      },
      winner: {
        video: "/videos/newzat/Winner.webm",
        videoWidth: 1920,
        videoHeight: 1080,
        introStartSec: 0,
        introEndSec: 5,
        mountDelaySec: 0,
        mountFadeSec: 0.75,
        unmountFadeSec: 0.3,
        outroPlaybackRate: 1,
        mainHoldMs: 0,
        unmountCompFadeSec: 1,
        nameTopPx: 0,
        nameFontSizePx: 36,
        frameUsSrc: "/images/newzat/RedFrame.svg",
        frameThemSrc: "/images/newzat/BlackFrame.svg",
        player1: {
          leftPx: 293,
          topPx: 0,
          widthPx: 140,
          heightPx: 195,
          rotateDeg: 0,
          imgHeightPx: 195,
          fallbackSrc: "/images/u1.jpg",
        },
        player2: {
          leftPx: 305,
          topPx: 0,
          widthPx: 140,
          heightPx: 195,
          rotateDeg: 0,
          imgHeightPx: 195,
          fallbackSrc: "/images/u2.jpg",
        },
      },
      cam: {
        usFrameSrc: "/images/newzat/usframe.svg",
        themFrameSrc: "/images/newzat/themframe.svg",
        frameWidthPx: 140,
        frameHeightPx: 195,
        frameLeftPx: 0,
        frameTopPx: 0,
        imageWidthPx: 140,
        imageHeightPx: 187,
        imageLeftPx: 0,
        imageTopPx: 5,
      },
    },
  },
};
