import type { ThemeConfig } from "./types";

/**
 * Cloned from zat, then tuned via /config for newzat videos/assets.
 * Synced from RTDB theme_configs/newzat.
 */
export const newzatTheme: ThemeConfig = {
  id: "newzat",
  landscape: {
    baloot: {
      cam: {
        topLeft: {
          frameSrc: "/images/newzat/usframe.svg",
          wrapWidthPx: 150,
          wrapHeightPx: 219,
          wrapLeftPx: 150,
          wrapTopPx: 0,
          frameWidthPx: 189,
          frameHeightPx: 233,
          frameLeftPx: -18,
          frameTopPx: 0,
          imageWidthPx: 135,
          imageHeightPx: 187,
          imageLeftPx: 6,
          imageTopPx: 33,
        },
        topRight: {
          frameSrc: "/images/newzat/themframe.svg",
          wrapWidthPx: 150,
          wrapHeightPx: 219,
          wrapLeftPx: -150,
          wrapTopPx: 0,
          frameWidthPx: 189,
          frameHeightPx: 233,
          frameLeftPx: -18,
          frameTopPx: 0,
          imageWidthPx: 135,
          imageHeightPx: 187,
          imageLeftPx: 6,
          imageTopPx: 33,
        },
        bottomLeft: {
          frameSrc: "/images/newzat/themframe.svg",
          wrapWidthPx: 150,
          wrapHeightPx: 219,
          wrapLeftPx: 150,
          wrapTopPx: -26,
          frameWidthPx: 189,
          frameHeightPx: 233,
          frameLeftPx: -18,
          frameTopPx: 0,
          imageWidthPx: 135,
          imageHeightPx: 179,
          imageLeftPx: 6,
          imageTopPx: 33,
        },
        bottomRight: {
          frameSrc: "/images/newzat/usframe.svg",
          wrapWidthPx: 150,
          wrapHeightPx: 219,
          wrapLeftPx: -154,
          wrapTopPx: -26,
          frameWidthPx: 189,
          frameHeightPx: 233,
          frameLeftPx: -18,
          frameTopPx: 0,
          imageWidthPx: 135,
          imageHeightPx: 187,
          imageLeftPx: 6,
          imageTopPx: 33,
        },
      },
      detail: {
        introEndSec: 3.5,
        introStartSec: 0,
        mainHoldMs: 1,
        mountDelaySec: 1.75,
        mountFadeSec: 0.75,
        outroPlaybackRate: 2,
        team1: {
          detailLeftPx: 0,
          detailTopPx: 300,
          detailWidthPx: 85,
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          nameLeftPx: 111,
          nameWidthPx: 257,
          scoreColor: "#ffffff",
          scoreFontSizePx: 34,
          scoreLeftPx: 14,
          sponsorLeftPx: 313,
          sponsorSrc: "/images/newzat/zat_white.svg",
          wrapHeightPx: 80,
          wrapLeftPx: 1003,
          wrapTopPx: 132,
          wrapWidthPx: 428,
        },
        team2: {
          detailRightPx: 0,
          detailTopPx: 300,
          detailWidthPx: 85,
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          nameLeftPx: 115,
          nameWidthPx: 257,
          scoreColor: "#ffffff",
          scoreFontSizePx: 35,
          scoreRightPx: -1,
          sponsorLeftPx: 23,
          sponsorSrc: "/images/newzat/zat_white.svg",
          wrapHeightPx: 97,
          wrapLeftPx: 475,
          wrapTopPx: 132,
          wrapWidthPx: 428,
        },
        unmountFadeSec: 1,
        video: "/videos/newzat/Full_Score.webm",
        videoHeight: 1080,
        videoWidth: 1920,
      },
      score: {
        introEndSec: 4,
        introStartSec: 0,
        mountDelaySec: 2.15,
        mountFadeSec: 0.5,
        outroPlaybackRate: 3,
        scoreTweenSec: 0.75,
        team1: {
          nameColor: "#ffffff",
          nameFontFamily: "DinNextRegular",
          nameFontSizePx: 28,
          nameLeftPx: 85,
          nameTopPx: 14,
          nameWidthPx: 200,
          scoreColor: "#ffffff",
          scoreFontSizePx: 26,
          scoreLeftPx: 0,
          sponsorLeftPx: 314,
          sponsorSrc: "/images/newzat/zat_white.svg",
          wrapHeightPx: 62,
          wrapLeftPx: 1037,
          wrapTopPx: 100,
          wrapWidthPx: 324,
        },
        team2: {
          nameColor: "#ffffff",
          nameFontFamily: "DinNextRegular",
          nameFontSizePx: 28,
          nameLeftPx: 50,
          nameTopPx: 4,
          nameWidthPx: 200,
          scoreColor: "#ffffff",
          scoreFontSizePx: 26,
          scoreLeftPx: 269,
          sponsorHeightPx: 70,
          sponsorLeftPx: -52,
          sponsorSrc: "/images/newzat/kfc.png",
          sponsorTopPx: -13,
          sponsorWidthPx: 70,
          wrapHeightPx: 43,
          wrapLeftPx: 552,
          wrapTopPx: 105,
          wrapWidthPx: 324,
        },
        unmountFadeSec: 0.5,
        video: "/videos/newzat/Corner_Score.webm",
        videoHeight: 1080,
        videoWidth: 1920,
      },
      winner: {
        enabled: true,
        frameThemSrc: "/images/newzat/BlackFrame.svg",
        frameUsSrc: "/images/newzat/RedFrame.svg",
        introEndSec: 5,
        introStartSec: 0,
        mainHoldMs: 250,
        mountDelaySec: 0,
        mountFadeSec: 0.75,
        nameFontSizePx: 60,
        nameHeightPx: 101,
        nameLeftPx: 673,
        nameTopPx: 29,
        outroPlaybackRate: 1,
        player1: {
          fallbackSrc: "/images/u1.jpg",
          heightPx: 195,
          imgHeightPx: 195,
          leftPx: 151,
          rotateDeg: 0,
          topPx: -99,
          widthPx: 140,
        },
        player2: {
          fallbackSrc: "/images/u2.jpg",
          heightPx: 195,
          imgHeightPx: 195,
          leftPx: 305,
          rotateDeg: 0,
          topPx: -99,
          widthPx: 140,
        },
        unmountCompFadeSec: 1,
        unmountFadeSec: 0.3,
        video: "/videos/newzat/Winner.webm",
        videoHeight: 1080,
        videoWidth: 1920,
      },
    },
  },
};
