import type { ThemeConfig } from "./types";

/**
 * Harvested from Qydha baloot landscape Vue screens.
 * Store still supplies live scores/names — this file is skin only.
 */
export const qydhaTheme: ThemeConfig = {
  id: "qydha",
  landscape: {
    baloot: {
      score: {
        video: "/videos/qydha/landscape/Corner_Score.webm",
        videoWidth: 1920,
        videoHeight: 1080,
        introStartSec: 0,
        introEndSec: 4.5,
        /** Matches video’s built-in intro — text fades in after this delay. */
        mountDelaySec: 2,
        mountFadeSec: 1.2,
        scoreTweenSec: 0.75,
        unmountFadeSec: 0.5,
        outroPlaybackRate: 2,
        team1: {
          wrapLeftPx: 970,
          wrapTopPx: 118,
          wrapWidthPx: 324,
          wrapHeightPx: 62,
          nameLeftPx: 56, // left-14
          nameWidthPx: 185,
          scoreLeftPx: 2,
          nameColor: "#ffffff",
          nameFontSizePx: 24,
          scoreColor: "#334155",
          scoreFontSizePx: 30,
        },
        team2: {
          wrapLeftPx: 621,
          wrapTopPx: 118,
          wrapWidthPx: 324,
          wrapHeightPx: 62,
          nameLeftPx: 82,
          nameWidthPx: 185,
          scoreRightPx: 2,
          nameColor: "#ffffff",
          nameFontSizePx: 24,
          scoreColor: "#334155",
          scoreFontSizePx: 30,
        },
      },
      // Harvested from components/Detail/Qydha/baloot/landscape.vue
      detail: {
        video: "/videos/qydha/landscape/Full_Score.webm",
        videoWidth: 1920,
        videoHeight: 1080,
        introStartSec: 0,
        introEndSec: 5,
        mountDelaySec: 3,
        mountFadeSec: 0.75,
        unmountFadeSec: 0.3,
        outroPlaybackRate: 2,
        mainHoldMs: 250,
        team1: {
          wrapLeftPx: 1062,
          wrapTopPx: 200,
          wrapWidthPx: 499,
          wrapHeightPx: 97,
          nameLeftPx: 28,
          nameWidthPx: 300,
          scoreLeftPx: -80,
          detailLeftPx: 0,
          detailTopPx: 175,
          detailWidthPx: 85,
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          scoreColor: "#334155",
          scoreFontSizePx: 45,
        },
        team2: {
          wrapLeftPx: 364,
          wrapTopPx: 200,
          wrapWidthPx: 499,
          wrapHeightPx: 97,
          nameLeftPx: 170,
          nameWidthPx: 300,
          scoreLeftPx: 480,
          scoreRightPx: 73,
          detailRightPx: 0,
          detailTopPx: 175,
          detailWidthPx: 85,
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          scoreColor: "#334155",
          scoreFontSizePx: 45,
        },
      },
      // Harvested from components/winner/Qydha/baloot/landscape.vue
      winner: {
        video: "/videos/qydha/landscape/Winner.webm",
        videoWidth: 1920,
        videoHeight: 1080,
        introStartSec: 0,
        introEndSec: 6,
        mountDelaySec: 1,
        mountFadeSec: 0.75,
        unmountFadeSec: 0.3,
        outroPlaybackRate: 1,
        mainHoldMs: 1000,
        unmountCompFadeSec: 3,
        nameTopPx: 160,
        nameFontSizePx: 36,
        player1: {
          leftPx: 34,
          topPx: -80,
          widthPx: 178,
          heightPx: 200,
          rotateDeg: 15,
          imgHeightPx: 250,
          fallbackSrc: "/images/u1.jpg",
        },
        player2: {
          leftPx: -190,
          topPx: -80,
          widthPx: 185,
          heightPx: 400,
          rotateDeg: -15,
          imgHeightPx: 250,
          fallbackSrc: "/images/u2.jpg",
        },
      },
      // No dedicated qydha cam frames yet — reuse zat SVGs
      cam: {
        usFrameSrc: "/images/zat/usframe.svg",
        themFrameSrc: "/images/zat/themframe.svg",
        frameWidthPx: 140,
        frameHeightPx: 195,
        imageHeightPx: 187,
        imageTopPx: 5,
      },
    },
  },
};
