import type { ThemeConfig } from "./types";

/**
 * Harvested from Qydha baloot landscape Vue screens.
 * Store still supplies live scores/names — this file is skin only.
 * Synced from RTDB theme_configs/qydha.
 */
export const qydhaTheme: ThemeConfig = {
  id: "qydha",
  landscape: {
    baloot: {
      detail: {
        introEndSec: 5,
        introStartSec: 0,
        mainHoldMs: 250,
        mountDelaySec: 3,
        mountFadeSec: 0.75,
        outroPlaybackRate: 2,
        team1: {
          detailLeftPx: 0,
          detailTopPx: 175,
          detailWidthPx: 85,
          nameLeftPx: 28,
          nameWidthPx: 300,
          scoreLeftPx: -80,
          wrapHeightPx: 97,
          wrapLeftPx: 1062,
          wrapTopPx: 200,
          wrapWidthPx: 499,
        },
        team2: {
          detailRightPx: 0,
          detailTopPx: 175,
          detailWidthPx: 85,
          nameLeftPx: 170,
          nameWidthPx: 300,
          scoreLeftPx: 480,
          scoreRightPx: 73,
          wrapHeightPx: 97,
          wrapLeftPx: 364,
          wrapTopPx: 200,
          wrapWidthPx: 499,
        },
        unmountFadeSec: 0.3,
        video: "/videos/qydha/landscape/Full_Score.webm",
        videoHeight: 1080,
        videoWidth: 1920,
      },
      score: {
        introEndSec: 4.5,
        introStartSec: 0,
        mountDelaySec: 2,
        mountFadeSec: 1.2,
        outroPlaybackRate: 2,
        scoreTweenSec: 0.75,
        team1: {
          nameLeftPx: 56,
          nameWidthPx: 185,
          scoreLeftPx: 2,
          wrapHeightPx: 62,
          wrapLeftPx: 970,
          wrapTopPx: 118,
          wrapWidthPx: 324,
        },
        team2: {
          nameLeftPx: 82,
          nameWidthPx: 185,
          scoreRightPx: 2,
          wrapHeightPx: 62,
          wrapLeftPx: 621,
          wrapTopPx: 118,
          wrapWidthPx: 324,
        },
        unmountFadeSec: 0.5,
        video: "/videos/qydha/landscape/Corner_Score.webm",
        videoHeight: 1080,
        videoWidth: 1920,
      },
      winner: {
        enabled: true,
        introEndSec: 6,
        introStartSec: 0,
        mainHoldMs: 1000,
        mountDelaySec: 1,
        mountFadeSec: 0.75,
        nameTopPx: 160,
        outroPlaybackRate: 1,
        player1: {
          fallbackSrc: "/images/u1.jpg",
          heightPx: 200,
          imgHeightPx: 250,
          leftPx: 34,
          rotateDeg: 15,
          topPx: -80,
          widthPx: 178,
        },
        player2: {
          fallbackSrc: "/images/u2.jpg",
          heightPx: 400,
          imgHeightPx: 250,
          leftPx: -190,
          rotateDeg: -15,
          topPx: -80,
          widthPx: 185,
        },
        unmountCompFadeSec: 3,
        unmountFadeSec: 0.3,
        video: "/videos/qydha/landscape/Winner.webm",
        videoHeight: 1080,
        videoWidth: 1920,
      },
    },
  },
};
