import type { ThemeConfig } from "./types";

/**
 * Harvested from Zat baloot landscape Vue screens + /config tuning.
 * Store still supplies live scores/names — this file is skin only.
 * Synced from RTDB theme_configs/zat.
 */
export const zatTheme: ThemeConfig = {
  id: "zat",
  landscape: {
    baloot: {
      cam: {
        topLeft: {
          frameSrc: "/images/zat/usframe.svg",
          wrapWidthPx: 140,
          wrapHeightPx: 195,
          wrapLeftPx: 0,
          wrapTopPx: 0,
          frameWidthPx: 140,
          frameHeightPx: 195,
          frameLeftPx: 0,
          frameTopPx: 0,
          imageWidthPx: 140,
          imageHeightPx: 187,
          imageLeftPx: 0,
          imageTopPx: 5,
        },
        topRight: {
          frameSrc: "/images/zat/themframe.svg",
          wrapWidthPx: 140,
          wrapHeightPx: 195,
          wrapLeftPx: 0,
          wrapTopPx: 0,
          frameWidthPx: 140,
          frameHeightPx: 195,
          frameLeftPx: 0,
          frameTopPx: 0,
          imageWidthPx: 140,
          imageHeightPx: 187,
          imageLeftPx: 0,
          imageTopPx: 5,
        },
        bottomLeft: {
          frameSrc: "/images/zat/themframe.svg",
          wrapWidthPx: 140,
          wrapHeightPx: 195,
          wrapLeftPx: 0,
          wrapTopPx: 0,
          frameWidthPx: 140,
          frameHeightPx: 195,
          frameLeftPx: 0,
          frameTopPx: 0,
          imageWidthPx: 140,
          imageHeightPx: 187,
          imageLeftPx: 0,
          imageTopPx: 5,
        },
        bottomRight: {
          frameSrc: "/images/zat/usframe.svg",
          wrapWidthPx: 140,
          wrapHeightPx: 195,
          wrapLeftPx: 0,
          wrapTopPx: 0,
          frameWidthPx: 140,
          frameHeightPx: 195,
          frameLeftPx: 0,
          frameTopPx: 0,
          imageWidthPx: 140,
          imageHeightPx: 187,
          imageLeftPx: 0,
          imageTopPx: 5,
        },
      },
      detail: {
        introEndSec: 3.22,
        introStartSec: 0,
        mainHoldMs: 251,
        mountDelaySec: 1.75,
        mountFadeSec: 0.75,
        outroPlaybackRate: 2,
        team1: {
          detailLeftPx: 0,
          detailTopPx: 400,
          detailWidthPx: 85,
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          nameLeftPx: 84,
          nameWidthPx: 300,
          scoreColor: "#ffffff",
          scoreFontSizePx: 40,
          scoreLeftPx: -10,
          sponsorLeftPx: 386,
          sponsorSrc: "/images/zat/zat_white.svg",
          wrapHeightPx: 97,
          wrapLeftPx: 1062,
          wrapTopPx: 62,
          wrapWidthPx: 499,
        },
        team2: {
          detailRightPx: 0,
          detailTopPx: 400,
          detailWidthPx: 85,
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          nameLeftPx: 115,
          nameWidthPx: 300,
          scoreColor: "#ffffff",
          scoreFontSizePx: 40,
          scoreRightPx: -7,
          sponsorLeftPx: 12,
          sponsorSrc: "/images/zat/zat_black.svg",
          wrapHeightPx: 97,
          wrapLeftPx: 364,
          wrapTopPx: 62,
          wrapWidthPx: 499,
        },
        unmountFadeSec: 1,
        video: "/videos/zat/Full_Score.webm",
        videoHeight: 1080,
        videoWidth: 1920,
      },
      score: {
        introEndSec: 3,
        introStartSec: 0,
        mountDelaySec: 2.15,
        mountFadeSec: 0.5,
        outroPlaybackRate: 2,
        scoreTweenSec: 0.75,
        team1: {
          nameColor: "#ffffff",
          nameFontSizePx: 28,
          nameLeftPx: 56,
          nameWidthPx: 185,
          scoreColor: "#ffffff",
          scoreFontSizePx: 26,
          scoreLeftPx: 0,
          sponsorLeftPx: 254,
          sponsorSrc: "/images/zat/zat_white.svg",
          wrapHeightPx: 62,
          wrapLeftPx: 978,
          wrapTopPx: 20,
          wrapWidthPx: 324,
        },
        team2: {
          nameColor: "#ffffff",
          nameFontSizePx: 28,
          nameLeftPx: 82,
          nameWidthPx: 185,
          scoreColor: "#ffffff",
          scoreFontSizePx: 26,
          scoreLeftPx: 269,
          sponsorLeftPx: 3,
          sponsorSrc: "/images/zat/zat_black.svg",
          wrapHeightPx: 62,
          wrapLeftPx: 621,
          wrapTopPx: 20,
          wrapWidthPx: 324,
        },
        unmountFadeSec: 0.3,
        video: "/videos/zat/Corner_Score.webm",
        videoHeight: 1080,
        videoWidth: 1920,
      },
      winner: {
        frameThemSrc: "/images/zat/BlackFrame.svg",
        frameUsSrc: "/images/zat/RedFrame.svg",
        introEndSec: 5,
        introStartSec: 0,
        mainHoldMs: 1,
        mountDelaySec: 2,
        mountFadeSec: 0.75,
        nameFontSizePx: 60,
        nameHeightPx: 100,
        nameLeftPx: 550,
        nameTopPx: 0,
        outroPlaybackRate: 1,
        player1: {
          fallbackSrc: "/images/u1.jpg",
          heightPx: 195,
          imgHeightPx: 195,
          leftPx: 308,
          rotateDeg: 0,
          topPx: -96,
          widthPx: 140,
        },
        player2: {
          fallbackSrc: "/images/u2.jpg",
          heightPx: 195,
          imgHeightPx: 195,
          leftPx: 154,
          rotateDeg: 0,
          topPx: -96,
          widthPx: 140,
        },
        unmountCompFadeSec: 1,
        unmountFadeSec: 0.3,
        video: "/videos/zat/Winner.webm",
        videoHeight: 1080,
        videoWidth: 1920,
      },
    },
  },
};
