import type { ThemeConfig } from "./types";

/**
 * Harvested from Zat baloot landscape Vue screens + /config tuning.
 * Store still supplies live scores/names — this file is skin only.
 */
export const zatTheme: ThemeConfig = {
  id: "zat",
  landscape: {
    baloot: {
      score: {
        video: "/videos/zat/Corner_Score.webm",
        videoWidth: 1920,
        videoHeight: 1080,
        introStartSec: 0,
        introEndSec: 3.5,
        mountDelaySec: 2.15,
        mountFadeSec: 0.5,
        scoreTweenSec: 0.75,
        unmountFadeSec: 0.3,
        outroPlaybackRate: 2,
        team1: {
          wrapLeftPx: 978,
          wrapTopPx: 20,
          wrapWidthPx: 324,
          wrapHeightPx: 62,
          nameLeftPx: 56,
          nameWidthPx: 185,
          scoreLeftPx: 0,
          sponsorSrc: "/images/zat/zat_white.svg",
          sponsorLeftPx: 254,
          nameColor: "#ffffff",
          nameFontSizePx: 28,
          scoreColor: "#ffffff",
          scoreFontSizePx: 26,
        },
        team2: {
          wrapLeftPx: 621,
          wrapTopPx: 20,
          wrapWidthPx: 324,
          wrapHeightPx: 62,
          nameLeftPx: 82,
          nameWidthPx: 185,
          scoreLeftPx: 269,
          sponsorSrc: "/images/zat/zat_black.svg",
          sponsorLeftPx: 3,
          nameColor: "#ffffff",
          nameFontSizePx: 28,
          scoreColor: "#ffffff",
          scoreFontSizePx: 26,
        },
      },
      detail: {
        video: "/videos/zat/Full_Score.webm",
        videoWidth: 1920,
        videoHeight: 1080,
        introStartSec: 0,
        introEndSec: 3.22,
        mountDelaySec: 1.75,
        mountFadeSec: 0.75,
        unmountFadeSec: 1,
        outroPlaybackRate: 2,
        mainHoldMs: 250,
        team1: {
          wrapLeftPx: 1062,
          wrapTopPx: 62,
          wrapWidthPx: 499,
          wrapHeightPx: 97,
          nameLeftPx: 84,
          nameWidthPx: 300,
          scoreLeftPx: -10,
          detailLeftPx: 0,
          detailTopPx: 400,
          detailWidthPx: 85,
          sponsorSrc: "/images/zat/zat_white.svg",
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          scoreColor: "#ffffff",
          scoreFontSizePx: 40,
        },
        team2: {
          wrapLeftPx: 364,
          wrapTopPx: 62,
          wrapWidthPx: 499,
          wrapHeightPx: 97,
          nameLeftPx: 115,
          nameWidthPx: 300,
          scoreRightPx: -7,
          detailRightPx: 0,
          detailTopPx: 400,
          detailWidthPx: 85,
          sponsorSrc: "/images/zat/zat_black.svg",
          sponsorLeftPx: 12,
          nameColor: "#ffffff",
          nameFontSizePx: 32,
          scoreColor: "#ffffff",
          scoreFontSizePx: 40,
        },
      },
      winner: {
        video: "/videos/zat/Winner.webm",
        videoWidth: 1920,
        videoHeight: 1080,
        introStartSec: 0,
        introEndSec: 5,
        mountDelaySec: 0,
        mountFadeSec: 0.75,
        unmountFadeSec: 0.3,
        outroPlaybackRate: 1,
        mainHoldMs: 0,
        unmountCompFadeSec: 1,
        nameTopPx: 0,
        nameFontSizePx: 36,
        frameUsSrc: "/images/zat/RedFrame.svg",
        frameThemSrc: "/images/zat/BlackFrame.svg",
        player1: {
          leftPx: 293,
          topPx: 0,
          widthPx: 140,
          heightPx: 195,
          rotateDeg: 0,
          imgHeightPx: 195,
          fallbackSrc: "/images/u1.jpg",
        },
        player2: {
          leftPx: 305,
          topPx: 0,
          widthPx: 140,
          heightPx: 195,
          rotateDeg: 0,
          imgHeightPx: 195,
          fallbackSrc: "/images/u2.jpg",
        },
      },
    },
  },
};
